server:
  port: 9000

spring:
  dataSource:
    name: datasource
    url: jdbc:mysql://192.168.199.201:3306/fanliba_main?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&useOldAliasMetadataBehavior=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    maxActive: 2
    maxIdle: 2
    minIdle: 2
    initialSize: 2
    validationQuery: select 1
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: false
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 3000
    maxWait: 3000
    jmxEnabled: true
    sqlShow : true
  redis:
     database: 1
     host: localhost
     password:
     port: 6379
     maxIdle: 300 # 最大空闲数
     seralizerType: JDK   # 序列化方式，HESSIAN 或 JDK
     # https://blog.csdn.net/truelove12358/article/details/78342167
  session:
    store-type: redis
    redis:
      namespace: ziboweb:session
      flush-mode: ON_SAVE # IMMEDIATE 或 ON_SAVE
    #https://docs.spring.io/spring-session/docs/current/reference/html5/guides/boot-redis.html
  server:
    session:
      timeout: 600 # Session timeout in seconds.

mybatis:
  type-aliases-package: com.zibowh.domain.entity
  mapperLocations: classpath:mapper/*.xml